name: Test Inclusive Language Checker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Inclusive Language Checker
        uses: ./LanguageChecker
        with:
          files: |
            test-file.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
